version: 2
jobs:
  build:
    working_directory: ~/ci-test
    docker:
      - image: node:8.10
        environment:
          NODE_ENV: production
    environment:
      NODE_ENV: production

    steps:
      - checkout
      - run:
          name: Install dependences
          command: npm install --silent
      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - build
